export const ITEMS_CATALOG = [
  // Papelaria
  { name: 'Papel A4', packagingName: 'Pacote', categoryId: 'papelaria' },
  { name: 'Bobina Térmica (80 x 30)', packagingName: 'Rolo', categoryId: 'papelaria' },
  { name: 'Bobina de Balança', packagingName: 'Rolo', categoryId: 'papelaria' },
  { name: 'Ribbon', packagingName: 'Unidade', categoryId: 'papelaria' },
  { name: 'Etiqueta Gôndola (S/Francho)', packagingName: 'Rolo', categoryId: 'papelaria' },
  { name: 'Etiqueta Branca Produto', packagingName: 'Rolo', categoryId: 'papelaria' },
  { name: 'Tinta Amarela - Comestível', packagingName: 'Frasco', categoryId: 'papelaria' },
  { name: 'Tinta Ciano - Comestível', packagingName: 'Frasco', categoryId: 'papelaria' },
  { name: 'Tinta Magenta - Comestível', packagingName: 'Frasco', categoryId: 'papelaria' },
  { name: 'Tinta Preta - Comestível', packagingName: 'Frasco', categoryId: 'papelaria' },
  { name: 'Tinta Preta', packagingName: 'Cartucho', categoryId: 'papelaria' },
  { name: 'Tinta Magenta', packagingName: 'Cartucho', categoryId: 'papelaria' },
  { name: 'Tinta Ciano', packagingName: 'Cartucho', categoryId: 'papelaria' },
  { name: 'Tinta Amarela', packagingName: 'Cartucho', categoryId: 'papelaria' },
  { name: 'Durex', packagingName: 'Rolo', categoryId: 'papelaria' },
  { name: 'Papel Fotográfico', packagingName: 'Pacote', categoryId: 'papelaria' },
  { name: 'Papel Adesivo', packagingName: 'Pacote', categoryId: 'papelaria' },
  { name: 'Grampo 26/6', packagingName: 'Caixa', categoryId: 'papelaria' },

  // Limpeza
  { name: 'Água Sanitária 5L', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Álcool 1L', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Bom Ar', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Bombril', packagingName: 'Pacote', categoryId: 'limpeza' },
  { name: 'Desinfetante 5L', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Detergente', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Espanador', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Esponja', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Lustra Móveis', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Multiuso', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Pá de Lixo', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Papel Higiênico', packagingName: 'Pacote', categoryId: 'limpeza' },
  { name: 'Papel Toalha', packagingName: 'Rolo', categoryId: 'limpeza' },
  { name: 'Pedra Sanitária', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Perfex', packagingName: 'Pacote', categoryId: 'limpeza' },
  { name: 'Rodo', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Sabão em Pó', packagingName: 'Pacote', categoryId: 'limpeza' },
  { name: 'Sabonete Líquido', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Saco de Lixo', packagingName: 'Pacote', categoryId: 'limpeza' },
  { name: 'Saco de Pano', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Vassoura', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Escova de Roupa', packagingName: 'Unidade', categoryId: 'limpeza' },
  { name: 'Cloro 5L', packagingName: 'Unidade', categoryId: 'limpeza' },
] as const
