export const ITEMS_CATALOG = [
  // Papelaria
  { name: 'Papel A4', unit: 'pacote', category: 'PAPELARIA' },
  { name: 'Bobina Térmica (80 x 30)', unit: 'rolo', category: 'PAPELARIA' },
  { name: 'Bobina de Balança', unit: 'rolo', category: 'PAPELARIA' },
  { name: 'Ribbon', unit: 'unidade', category: 'PAPELARIA' },
  { name: 'Etiqueta Gôndola (S/Francho)', unit: 'rolo', category: 'PAPELARIA' },
  { name: 'Etiqueta Branca Produto', unit: 'rolo', category: 'PAPELARIA' },
  { name: 'Tinta Amarela - Comestível', unit: 'frasco', category: 'PAPELARIA' },
  { name: 'Tinta Ciano - Comestível', unit: 'frasco', category: 'PAPELARIA' },
  { name: 'Tinta Magenta - Comestível', unit: 'frasco', category: 'PAPELARIA' },
  { name: 'Tinta Preta - Comestível', unit: 'frasco', category: 'PAPELARIA' },
  { name: 'Tinta Preta', unit: 'cartucho', category: 'PAPELARIA' },
  { name: 'Tinta Magenta', unit: 'cartucho', category: 'PAPELARIA' },
  { name: 'Tinta Ciano', unit: 'cartucho', category: 'PAPELARIA' },
  { name: 'Tinta Amarela', unit: 'cartucho', category: 'PAPELARIA' },
  { name: 'Durex', unit: 'rolo', category: 'PAPELARIA' },
  { name: 'Papel Fotográfico', unit: 'pacote', category: 'PAPELARIA' },
  { name: 'Papel Adesivo', unit: 'pacote', category: 'PAPELARIA' },
  { name: 'Grampo 26/6', unit: 'caixa', category: 'PAPELARIA' },

  // Limpeza
  { name: 'Água Sanitária 5L', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Álcool 1L', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Bom Ar', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Bombril', unit: 'pacote', category: 'LIMPEZA' },
  { name: 'Desinfetante 5L', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Detergente', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Espanador', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Esponja', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Lustra Móveis', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Multiuso', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Pá de Lixo', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Papel Higiênico', unit: 'pacote', category: 'LIMPEZA' },
  { name: 'Papel Toalha', unit: 'rolo', category: 'LIMPEZA' },
  { name: 'Pedra Sanitária', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Perfex', unit: 'pacote', category: 'LIMPEZA' },
  { name: 'Rodo', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Sabão em Pó', unit: 'pacote', category: 'LIMPEZA' },
  { name: 'Sabonete Líquido', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Saco de Lixo', unit: 'pacote', category: 'LIMPEZA' },
  { name: 'Saco de Pano', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Vassoura', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Escova de Roupa', unit: 'unidade', category: 'LIMPEZA' },
  { name: 'Cloro 5L', unit: 'unidade', category: 'LIMPEZA' },
] as const
